
catalogue:	## Installing Catalogue
	@bash components/catalogue.sh

mongodb:	## Installing MongoDB
	@bash components/mongodb.sh

redis:	## Installing Redis
	@bash components/redis.sh

user:	## Installing User
	@bash componentes/user.sh

cart:	## Installing Cart
	@bash componentes/cart.sh

mysql:	## Installing Mysql
	@bash componentes/mysql.sh

shipping:	## Installing Shipping
	@bash componentes/shipping.sh

rabbitmq:	## Installing Rabbitmq
	@bash componentes/rabbitmq.sh

payment:	## Installing Payment
	@bash componentes/payment.sh

frontend:	## Installing Frontend
	@bash componentes/frontend.sh



